name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the site in the jekyll/builder container
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy
      uses: actions/checkout@master
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
        PUBLISH_BRANCH: mater
        PUBLISH_DIR: docs
